name: Test failure scenarios

on:
  workflow_dispatch:
    inputs:
      directory:
        type: string
        default: test-data/maven/simple
        required: true

permissions: read-all

jobs:
  test:
    name: Test Failure

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run local Action
        uses: ./
        with:
          directory: ${{ inputs.directory }}